<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.9</Version>
    <Description>Replaces the teleport menu with a new window that aims to keep the original feel while adding new features. The new menu includes content tracking for all locations, a drop-down menu to filter by content, and the introduction of two new location tabs named Independent Nations and Beyond the Source to replace the Other tab.</Description>
    <PackageProjectUrl>https://github.com/Lambda931/BetterTeleport</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="BetterTeleport.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Classes\" />
    <Folder Include="Images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.14.0" />
  </ItemGroup>
</Project>
