<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.1</Version>
    <Description>A plugin that gives the player a better teleport menu.</Description>
    <PackageProjectUrl>https://github.com/Lambda931/BetterTeleport</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="BetterTeleport.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Classes\" />
    <Folder Include="Images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.14.0" />
  </ItemGroup>
</Project>
